baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'My CraftCMS vite site'
primary: true
siteGroup: 896068a9-0d17-4750-b2d7-14c9dddd332d # My CraftCMS vite site
sortOrder: 1
