altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fe6577e5-1f0e-4dbb-9f8d-fb5e43e010f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-26T13:10:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b051166a-cb64-4a58-92ed-8c5489cd2807
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30d0836b-5217-448f-8905-8c14077fdb35
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
